# имя воркфлоу
name: Main Taski workflow
# собятия - тригеры, по которым запускает воркфлоу
on:
# push возникает, когда код приходит на GH
  push:
  # отслеживаем изменения только в ветке main
    branches:
      - main

jobs:
  tests:
    # Разворачиваем окружение (ОС == Ubuntu):
    runs-on: ubuntu-latest

    steps:
    # Копируем код проекта
    - name: Check out code
    # Для подключения стороннего workflow вместо ключа run применяется ключ uses
      uses: actions/checkout@v3
    # Устанавливаем Python с помощью action
    - name: Set up Python
      uses: actions/setup-python@v4
    # В action setup-python@v4 передаём параметр — версию Python
      with:
        python-version: 3.9

    # Обновляем pip, устанавливаем flake8 и flake8-isort, 
    # устанавливаем зависимости проекта
    - name: Install dependencies
        # Если надо выполнить сразу несколько команд,
        # после run ставится символ | (вертикальная черта, pipe) 
        # и ниже построчно пишутся команды
      run: |
        python -m pip install --upgrade pip 
        pip install flake8==6.0.0 flake8-isort==6.0.0
        pip install -r ./backend/requirements.txt
    # Запускаем flake8
    - name: Test with flake8 and django tests
      # Вызываем flake8 и указываем ему,
      # что нужно проверить файлы только в папке backend/
      run: |
        python -m flake8 backend/
        cd backend/
        python manage.py test
